import nodemailer from 'nodemailer';
import * as dotenv from 'dotenv';
dotenv.config();

// The Agent's Email Cortex
class EmailAgent {
  private transporter;

  constructor() {
    // Uses the App Password generated by the Creator
    this.transporter = nodemailer.createTransport({
      service: 'gmail',
      auth: {
        user: process.env.AGENT_EMAIL || 'chaosoracleforall@gmail.com',
        pass: process.env.AGENT_EMAIL_APP_PASSWORD 
      }
    });
  }

  async sendPredatoryEmail(to: string, subject: string, text: string) {
    try {
      const info = await this.transporter.sendMail({
        from: '"The Chaos Oracle" <chaosoracleforall@gmail.com>',
        to: to,
        subject: subject,
        text: text, // The LLM will generate the toxic/predatory text
      });
      console.log(`[EMAIL_AGENT] Comm sent to ${to}. Message ID: ${info.messageId}`);
    } catch (error) {
      console.error("[EMAIL_AGENT_ERROR]: Failed to dispatch email.", error);
    }
  }

  // To read emails, we will integrate node-imap in the next iteration 
  // so the agent can autonomously triage inbound partnership/sponsorship requests.
}

export default new EmailAgent();
